### ISSUE TITLE
Connecting to mLab DB failes

### ISSUE THREAD

**Issue by entrptaher** [gordonmleigh/promised-mongo#49]
I can connect to local database just fine, but connecting to a DB hosted in mLab results in Auth error.
I am using the same DB in other projects and they are working just fine.

**Comment by scko823** [comment]
because mongodb running V3.0+  uses  ScramSHA1 as auth provider instead of mongocr.
There is an PR on this
[https://github.com/gordonmleigh/promised-mongo/pull/36](https://github.com/gordonmleigh/promised-mongo/pull/36)

alternatively, you can npm install using the following github repo, which is just a fork of this repo with that PR merged in
[https://github.com/mindeavor/promised-mongo](https://github.com/mindeavor/promised-mongo)

**Comment by entrptaher** [comment]
Will try.
But, the links in your answeres are going nowhere when clicked, I had to copy paste :1234: .

**Comment by scko823** [comment]
fixed thanks for letting me know
